# Generated by Django 3.1 on 2020-09-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=17, unique=True)),
                ('email', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=255)),
                ('logradouro', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id_consumidor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('sobrenome', models.CharField(max_length=60)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('senha', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('logradouro', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_cartao', models.CharField(blank=True, max_length=16, null=True)),
                ('codigo_seguranca', models.CharField(blank=True, max_length=3, null=True)),
                ('titular_cartao', models.CharField(blank=True, max_length=60, null=True)),
                ('validade_cartao', models.DateField(blank=True, null=True)),
                ('limite_compra', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'consumidor',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('parcela', models.CharField(blank=True, max_length=2, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=15, null=True)),
                ('status_pedido', models.CharField(blank=True, max_length=20, null=True)),
                ('data_pedido', models.DateField(blank=True, null=True)),
                ('cliente_id_cliente', models.ForeignKey(db_column='cliente_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='base.cliente')),
                ('consumidor_id_consumidor', models.ForeignKey(db_column='consumidor_id_consumidor', on_delete=django.db.models.deletion.DO_NOTHING, to='base.consumidor')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('categoria', models.CharField(blank=True, max_length=20, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='base.cliente')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='base.pedido')),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.DO_NOTHING, to='base.produto')),
            ],
            options={
                'db_table': 'pedido_produto',
            },
        ),
        migrations.CreateModel(
            name='EnderecoEntrega',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('id_consumidor', models.ForeignKey(db_column='id_consumidor', on_delete=django.db.models.deletion.DO_NOTHING, to='base.consumidor')),
            ],
            options={
                'db_table': 'endereco_entrega',
            },
        ),
    ]
